default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5
  port: 5432

development:
  <<: *default
  database: myapp_development

ci:
  <<: *default
  database: myapp_test
  host: localhost

test:
  <<: *default
  database: myapp_test
  host: <%= ENV['CI'] ? 'localhost' : 'db' %>